Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,15 +13,27 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
+      
+    - name: Check that secrets are not empty
+      run: |
+        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+          echo "❌ DOCKER_USERNAME is empty or missing"
+          exit 1
+        else
+          echo "✅ DOCKER_USERNAME is set"
+        fi
+
+        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+          echo "❌ DOCKER_PASSWORD is empty or missing"
+          exit 1
+        else
+          echo "✅ DOCKER_PASSWORD is set"
+        fi
+
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
       
-    - name: Check that secrets are not empty
-      run: |
-        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "Username secret is empty"; exit 1; fi
-        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "Password secret is empty"; exit 1; fi
-
     - name: Login to DockerHub
       uses: docker/login-action@v3
       with:
